name: IPTV Auto Merge

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch:      

# This block is MANDATORY to allow the bot to save the file back to your repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Merger
        run: python main.py

      
- name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add all_channels.m3u
          # This line prevents the "nothing to commit" error
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update $(date)" && git push origin 